[FEAT] 게시판 기능 구현
Team-Capple/Capple-Server pull request #131
Opened 2024-08-19 18:05 UTC by kyxxgsoo

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feat/#128/boardAPI -> develop

### 변경 사항
- 게시글 작성 API 구현
- 카테고리별 게시글 조회 API 구현
- 게시글 삭제 API 구현
- 게시글 검색 API 구현
- 게시글 좋아요 토글 API 구현

### 테스트 결과
일정 관계상... 테스트코드는 추후에 짜도록 하겠습니다. (예외처리 잘 해놨어요 ㅠㅠ...)
<img width="536" alt="image" src="https://github.com/user-attachments/assets/915bb5ed-3c33-44d0-8fc2-ad1d24b367f9">

2024-08-19 22:09 UTC, jaewonLeeKOR requested changes
의견 남겨주세요.

2024-08-19 22:09 UTC, jaewonLeeKOR commented on src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
> +    @Query("SELECT b FROM Board b WHERE b.content LIKE %:keyword%")
이 방식의 like문을 사용은 복잡도의 굉장한 상승을 야기할 수 밖에 없는데, 중간에 들어가는 키워드를 찾아야하는 상황인가요?

2024-08-19 22:09 UTC, jaewonLeeKOR commented on src/main/java/com/server/capple/domain/board/repository/BoardHeartRedisRepository.java
> +        Set<String> keys = redisTemplate.keys(BOARD_HEART_KEY_PREFIX + "*"); // 모든 키 조회
저장된 좋아요를 모두 불러온다는건 너무 큰 코스트가 드는 작업일거 같아요.
대안을 구상해보는게 좋을거 같아요.
어떤 상황에서 쓰이는 메서드인기요?

2024-08-20 00:20 UTC, tnals2384 commented on src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
> +            Board board
board id만 넘겨줘도 될 것 같은데 board 자체를 넘겨주는 이유는 코드 통일성 때문인지 궁금합니다!!

2024-08-21 03:39 UTC, kyxxgsoo commented on src/main/java/com/server/capple/domain/board/repository/BoardHeartRedisRepository.java
> +        Set<String> members = redisTemplate.opsForSet().members(key);
그런 내용이 있는지 몰라서.. 한 번 찾아보고 답변 다시 달겠습니다!

2024-08-21 03:40 UTC, kyxxgsoo commented on src/main/java/com/server/capple/domain/board/repository/BoardRepository.java
> +    @Query("SELECT b FROM Board b WHERE b.content LIKE %:keyword%")
넵 content 사이에 있는 키워드를 찾아야 하는 상황인데, 혹시 더 효율적인 방법이 있을까요?.. 저도 찾아보는대로 다시 답변 남겨놓도록 하겠습니다!

2024-08-21 03:40 UTC, kyxxgsoo commented on src/main/java/com/server/capple/domain/board/repository/BoardHeartRedisRepository.java
> +        Set<String> keys = redisTemplate.keys(BOARD_HEART_KEY_PREFIX + "*"); // 모든 키 조회
아 이 기능은 지금 당장은 쓰이지 않는 기능이고, 프로필 들어가면 본인이 좋아요 누른 보드를 조회할 수 있는 기능을 위해 추가적으로 만들어 놓은 기능입니다!..

2024-08-21 03:41 UTC, kyxxgsoo commented on src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
> +            Board board
코드 통일성때문에 보드로 값을 넘기기는 하는데, 수정해도 되는 코드입니다!...

2024-08-21 03:42 UTC, kyxxgsoo commented on src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
> +            Board board
다 id값만 넘기도록 통일할까요? 저렇게 해놓은 이유는 다른 매퍼들은 엔티티 내부의 다른 필드를 가져와야 할 때가 있어서 객체 자체를 넘길 때가 있는데, 그 코드와 통일성을 유지하기 위해 이렇게 작성해놨습니다!

2024-08-21 03:53 UTC, jaewonLeeKOR commented on src/main/java/com/server/capple/domain/board/mapper/BoardMapper.java
> +            Board board
dto로 전체 entity 데이터를 보내주는 형식은 좋지 않습니다
엔드포인트의 dto가 엔티티에 종속이 생기기도 하고 반환 패킷 자체가 커지므로 수정하는것이 좋을거 같아요

2024-08-22 05:48 UTC, tnals2384 approved these changes

2024-08-25 10:33 UTC, jaewonLeeKOR commented on src/main/java/com/server/capple/domain/board/entity/BoardType.java
> +@RequiredArgsConstructor
enum은 `@RequiredArgsConstructor` 가 필요없지 않나요?

2024-08-25 12:15 UTC, merged